apiVersion: apps.tanzu.vmware.com/v1alpha1
kind: ContainerApp
spec:
  build:
    path: "."
    buildpacks: {}
    env:
      - name: BP_JVM_VERSION
        value: "21"

  nonSecretEnv:
    - name: IS_WORKER
      value: "false"

  replicas: 1

  resources:
    cpu: 500m
    memory: 128Mi
